import { Metadata } from "next";
import { Roboto } from "next/font/google"; // Mengimpor font Roboto
import "./globals.css";

// Menggunakan font Roboto dengan variasi berat (weight)
const roboto = Roboto({
  weight: ["100", "400", "500", "700", "900"], // Variasi berat yang tersedia
  subsets: ["latin"], // Subset untuk mengurangi ukuran font jika hanya menggunakan karakter tertentu
});

export const metadata: Metadata = {
  title: "Sistem Perpindahan Penduduk",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
